{
 "title": "Endlessh",
 "description": "Dashboard for endlessh",
 "tags": [ "prometheus" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=~\"endlessh.*\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(up{cluster=~\"$cluster\",job=~\"endlessh.*\"}, namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(up{cluster=~\"$cluster\",namespace=~\"$namespace\",job=~\"endlessh.*\"}, job)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(up{cluster=~\"$cluster\",namespace=~\"$namespace\",job=~\"$job\"}, service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(up{cluster=~\"$cluster\",namespace=~\"$namespace\",job=~\"$job\",service=~\"$service\"}, pod)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{cluster=~\"$cluster\",namespace=~\"$namespace\",job=~\"$job\",service=~\"$service\",pod=~\"$pod\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(endlessh_client_open_count{cluster=~\"$cluster\",namespace=~\"$namespace\",job=~\"$job\",service=~\"$service\",pod=~\"$pod\",instance=~\"$instance\"} - endlessh_client_open_count{cluster=~\"$cluster\",namespace=~\"$namespace\",job=~\"$job\",service=~\"$service\",pod=~\"$pod\",instance=~\"$instance\"} offset $__interval) > 0 or (endlessh_client_open_count{cluster=~\"$cluster\",namespace=~\"$namespace\",job=~\"$job\",service=~\"$service\",pod=~\"$pod\",instance=~\"$instance\"}!=0 unless endlessh_client_open_count{cluster=~\"$cluster\",namespace=~\"$namespace\",job=~\"$job\",service=~\"$service\",pod=~\"$pod\",instance=~\"$instance\"} offset $__interval)",
     "legendFormat": "Seen {{ip}}"
    },
    {
     "expr": "(endlessh_client_trapped_time_seconds{cluster=~\"$cluster\",namespace=~\"$namespace\",job=~\"$job\",service=~\"$service\",pod=~\"$pod\",instance=~\"$instance\"} - endlessh_client_trapped_time_seconds{cluster=~\"$cluster\",namespace=~\"$namespace\",job=~\"$job\",service=~\"$service\",pod=~\"$pod\",instance=~\"$instance\"} offset $__interval) > 0 or (endlessh_client_trapped_time_seconds{cluster=~\"$cluster\",namespace=~\"$namespace\",job=~\"$job\",service=~\"$service\",pod=~\"$pod\",instance=~\"$instance\"}!=0 unless endlessh_client_trapped_time_seconds{cluster=~\"$cluster\",namespace=~\"$namespace\",job=~\"$job\",service=~\"$service\",pod=~\"$pod\",instance=~\"$instance\"} offset $__interval)",
     "legendFormat": "Trapped {{ip}}"
    }
   ]
  },
  {
   "title": "Trapped Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 36 }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(endlessh_sent_bytes_total{cluster=~\"$cluster\",namespace=~\"$namespace\",job=~\"$job\",service=~\"$service\",pod=~\"$pod\",instance=~\"$instance\"}[$__range]))",
     "legendFormat": "Bytes sent by endlessh"
    }
   ]
  },
  {
   "title": "Unique IPs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 36 }
   ]
  },
  {
   "title": "Latest Connection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 36 }
   ]
  },
  {
   "title": "Current Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min((sum by (cluster,namespace,job,service,pod,instance) (endlessh_client_open_count_total{cluster=~\"$cluster\",namespace=~\"$namespace\",job=~\"$job\",service=~\"$service\",pod=~\"$pod\",instance=~\"$instance\"}) - sum by (cluster,namespace,job,service,pod,instance) (endlessh_client_closed_count_total{cluster=~\"$cluster\",namespace=~\"$namespace\",job=~\"$job\",service=~\"$service\",pod=~\"$pod\",instance=~\"$instance\"})), 0) and on(cluster,namespace,job,service,pod,instance) up{cluster=~\"$cluster\",namespace=~\"$namespace\",job=~\"$job\",service=~\"$service\",pod=~\"$pod\",instance=~\"$instance\"} == 1) or vector(0)",
     "legendFormat": "Open Connections"
    }
   ]
  },
  {
   "title": "Concurrent Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Connections by Country",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 36 }
   ]
  },
  {
   "title": "Locations",
   "type": "geomap",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "panelId": 36 }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "panelId": 36 }
   ]
  }
 ]
}