name: On pull request

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - 'dashboard/*'
      - 'examples/*'
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.26.1'
          cache: true
      - name: Install dependencies
        run: go mod download
      - name: Run Tests
        run: go test -v ./...
